import os

import os

def generate_html(chat_id, user_links, link_metadata,first_name):
    """Generate a mobile-friendly HTML file with link history and metadata."""
    # Ensure the directory exists
    directory = "/app/storage/links_history"
    if not os.path.exists(directory):
        os.makedirs(directory)

    # Start generating the HTML content
    history_html = f"""
    <html>
    <head>
        <title>{first_name} Links History</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            body {{
                background-color: #f4f7f6;
                margin: 0;
                padding: 0;
                color: #333;
                font-family: Arial, sans-serif;
            }}
            .container {{
                max-width: 600px;
                margin: 20px auto;
                background-color: #fff;
                padding: 15px;
                border-radius: 8px;
                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
                position: relative;
            }}
            h1 {{
                color: #2c3e50;
                text-align: center;
                font-size: 1.8rem;
                margin-bottom: 15px;
            }}
            .link-card {{
                background-color: #ecf0f1;
                margin: 15px 0;
                padding: 10px;
                border-radius: 4px;
                box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
            }}
            .link-card h2 {{
                font-size: 1.2rem;
                color: #34495e;
                margin: 0 0 10px;
            }}
            .link-card p {{
                font-size: 0.9rem;
                color: #7f8c8d;
                margin: 5px 0;
            }}
            .link-card a {{
                text-decoration: none;
                color: #2980b9;
                font-weight: bold;
            }}
            .link-card a:hover {{
                text-decoration: underline;
            }}
            footer {{
                text-align: center;
                font-size: 0.8rem;
                color: #7f8c8d;
                margin-top: 20px;
            }}
            /* Position the logo in the top left corner */
            .logo {{
                position: absolute;
                top: 15px;
                left: 15px;
                width: 60px; /* Adjust the size as needed */
                height: auto;
            }}
            @media (max-width: 768px) {{
                .container {{
                    padding: 10px;
                }}
                h1 {{
                    font-size: 1.5rem;
                }}
                .link-card {{
                    padding: 8px;
                }}
                .link-card h2 {{
                    font-size: 1rem;
                }}
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <!-- Logo at the top left -->
            <img src="/static/enrichly_logo.jpg" class="logo" alt="Enrichly Logo">

            <h1>Link History for User {chat_id}</h1>
    """

    # Loop through each link and its metadata
    for i, link in enumerate(user_links.get(chat_id, [])):
        metadata = link_metadata.get(chat_id, [])[i] if i < len(link_metadata.get(chat_id, [])) else {}

        history_html += f"""
        <div class="link-card">
            <h2><a href="{metadata.get('url', link)}" target="_blank">{metadata.get('title', 'Untitled')}</a></h2>
            <p><strong>Category:</strong> {metadata.get('category', 'Unknown')}</p>
            <p><strong>Description:</strong> {metadata.get('description', 'No description available.')}</p>
            {"<p><strong>Price:</strong> $" + metadata['price'] + "</p>" if "price" in metadata else ""}
            {"<p><strong>Content:</strong> " + metadata['content'][:200] + "...</p>" if "content" in metadata else ""}
        </div>
        """

    # Add footer and close HTML tags
    history_html += """
            <footer>
                <p>Generated by Enrichly</p>
            </footer>
        </div>
    </body>
    </html>
    """

    # Save the HTML file
    file_path = os.path.join(directory, f"{chat_id}_history.html")
    with open(file_path, "w") as file:
        file.write(history_html)

    # Return the link to the generated HTML page
    return f"https://flask-production-4c83.up.railway.app/storage/links_history/{chat_id}_history.html"

